/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jlite;

import jlite.lexer.Scanner;
import jlite.parser.parser;
import jlite.parser.Ast;
import java.io.*;

public class App {
    public static void main(String[] argv) {
        for (int i = 0; i < argv.length; i++) {
            String fileLoc = argv[i];
            try {
                Ast.Prog prog = parser.parse(fileLoc);
                System.out.println(prog.print());
            }
            catch (Exception e) {
                System.out.println(e);
            }
        }
    }
}
